name: Deploy to Cloud Functions

on:
  push:
    branches:
      - no_history

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy my_function \
          --runtime python310 \
          --trigger-http \
          --entry-point my_function \
          --region europe-west3 \
          --allow-unauthenticated \
          --no-gen2